### ISSUE TITLE
Create a Collection of JavaScript Free Courses

### ISSUE THREAD

**Issue by smv1999** [smv1999/JavaScript-Series#1]
Add free online resources that are great for beginners to start with.
Add free online resources for learning MERN/ MEAN stack.

**Comment by MannyP31** [comment]
Hello , shall I add some free udemy course link to this?

**Comment by smv1999** [comment]
Sure @MannyP31 , you can go ahead!

**Comment by MannyP31** [comment]
Thanks

**Comment by MannyP31** [comment]
Do I have to create a new repo for that?

**Comment by smv1999** [comment]
No. you can add the course links in the existing [Readme.md](https://github.com/smv1999/JavaScript-Series#readme) file itself and make a PR.

**Comment by MannyP31** [comment]
okay then !!

**Comment by MannyP31** [comment]
Now you may remove the issue . It has been solved !!😊
